### PR TITLE
validate on submission

### PR DESCRIPTION
**Pull request by jhsu**
validates the form on submission

calls the user passed submit handler after state has been updated so it gets the correct form status

updated the default story to reflect this

addresses #7

### CODE REVIEW

**Comment by ffxsam** [comment]
Awesome work!!

**Comment by ffxsam** [comment]
@jhsu This introduced a bug. I had a form that was totally valid, yet the form status passed to the submit function said the form was not valid.

**Comment by jhsu** [comment]
@ffxsam oh yikes! want to revert it for now?

**Comment by ffxsam** [comment]
Yep, done, and I unpublished on npm. I don't have time at the moment to whip up a reproduction, but let me know if you manage to find the issue.

**Comment by jhsu** [comment]
@ffxsam I've kinda made some changes on https://github.com/jhsu/formous/commits/jhsu-develop that'll solve it and does some other stuff. If you want, maybe we can chat on gitter or something?

**Comment by ffxsam** [comment]
@jhsu Sure! Just added you to the room for this repo. I'm there now.

**Comment by fredrik-sogaard** [comment]
@ffxsam @jhsu Is there any updated version where this works properly?

**Comment by ffxsam** [comment]
Nope, not yet. This is under code freeze for now while 1.0 is being worked on, so hang tight. Of course you're more than welcome to also fork the repo and hack it to work as you need!

**Pull request merged**
